[tool.isort]
line_length = 80

[tool.autopep8]
max_line_length = 80
ignore = "E731"

[tool.pylint]
disable = """comprehension-escape, redefined-outer-name, invalid-name,
           unused-wildcard-import, unsubscriptable-object,
           cell-var-from-loop, wildcard-import, ungrouped-imports"""
notes = """XXX, TODO"""

max-line-length = 80
max-module-lines = 4000

max-args = 7
max-locals = 35
max-statements = 100
max-attributes = 30

variable-naming-style = "any"
class-naming-style = "PascalCase"
module-naming-style = "snake_case"
class-attribute-naming-style = "any"
method-naming-style = "snake_case"
function-naming-style = "snake_case"
argument-naming-style = "any"
const-naming-style = "UPPER_CASE"
